#### general settings
name: RAWALIGN
use_tb_logger: True
model: rawalign
distortion: sr
scale: 80
save_img: True
gpu_ids: [2]

#### datasets
datasets:
  train:
    name: rawdata
    mode: raw
    dataroot: /home/work/ssd2/datasets/RawAlign/train_data
    use_shuffle: true
    n_workers: 16  # per GPU
    batch_size: 8
    image_size: [480, 480]
    data_suffix: '*.BGGR'
    inheight: 3072
    inwidth: 4096
    black_level: 1024
    white_level: 16383
    target_pattern: bggr
    input_pattern: bggr
    use_flip: True
    use_rot: True
  val:
    name: rawtest
    mode: raw
    dataroot: /home/work/ssd2/datasets/RawAlign/test_data
    data_suffix: '*.BGGR'
    inheight: 3072
    inwidth: 4096
    black_level: 1024
    white_level: 16383
    target_pattern: bggr
    input_pattern: bggr

#### network structures
network_G:
  which_model_G: xabaraw
  
#### path
path:
  root: /home/work/ssd2/hezhipeng/result/rawalign
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-3
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.999
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-8
  weight_decay: 0.0001

  pixel_criterion: cb
  pixel_weight: 1.0

  manual_seed: 1234
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
