#### general settings
name: RAFT-hzp
use_tb_logger: True
model: align
distortion: sr
scale: 8
save_img: False
gpu_ids: [2, 3]

#### datasets
datasets:
  train:
    name: chairs
    mode: Align
    dataroot: /home/work/ssd1/datasets/flyingchairs/FlyingChairs_release
    
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 10
    image_size: [368, 496]
    add_noise: false
    stage: chairs
  val:
    name: ['kitti']    #chairs, sintel, kitti
    mode: Align
    dataroot_chairs: /home/work/ssd1/datasets/flyingchairs/FlyingChairs_release
    dataroot_sintel: /home/work/ssd1/datasets/Sintal/Sintal_images
    dataroot_kitti: /home/work/ssd1/datasets/KITTI2015/KITTI

#### network structures
network_G:
  which_model_G: RAFT_HZP
  small: true
  alternate_corr: false
  mixed_precision: false
  iters: 12
  dropout: 0
  
#### path
path:
  root: /home/hezhipeng/codes/result/BasicAlign
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 0.0004
  #lr_scheme: CosineAnnealingLR_Restart
  #beta1: 0.9
  #beta2: 0.99
  #warmup_iter: -1  # no warm up
  #T_period: [250000, 250000, 250000, 250000]
  #restarts: [250000, 500000, 750000]
  #restart_weights: [1, 1, 1]
  eta_min: !!float 1e-8
  weight_decay: 0.0001

  pixel_criterion: sequence_loss
  pixel_weight: 1.0
  gamma: 0.8

  clip: 1.0

  manual_seed: 1234
  niter: 100000
  niter: 20
  val_freq: !!float 5e3
  #val_freq: !!float 20

#### logger
logger:
  print_freq: 100
  print_freq: 10
  save_checkpoint_freq: !!float 5e3
  save_checkpoint_freq: !!float 20
